apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: webapps
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
